config/routes.rb
Rails.application.routes.draw do  delete 'item_orders/destroy'
  get 'orders/new'
  get 'orders/show'

  get 'line_items/create'
  get 'login'=>"sessions#new"
  post 'login'=>"sessions#create"
  delete "logout"=>"sessions#destroy"
get 'signup' => 'users#new'
root 'static_pages#home'
  get 'hello'=>'say#hello'
  get 'bye'=>'say#bye'

  resources "products"
  resources "users"
  resources 'carts'
  resources 'orders'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items,:dependent=>:destroy
	def add_product(product_id)
		current_item= line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity+=1
			current_item.product.proamount-=1
			current_item.product.update_attributes(:proamount=>current_item.product.proamount)
		else
			current_item = line_items.build(:product_id=>product_id)
			current_item.product.proamount-=1
			current_item.product.update_attributes(:proamount=>current_item.product.proamount)
		end
		current_item
	end
	def emptycart(product_id)
		current_item= line_items.find_by_product_id(product_id)
		current_item.product.proamount+=current_item.quantity
		current_item.product.update_attributes(:proamount=>current_item.product.proamount)
	end
	def total_price
		line_items.to_a.sum{|item| item.total_price}
	end

end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
	belongs_to :order
	def total_price
		price * amount
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
	def total_price
		product.proprice * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	default_scope -> { order(created_at: :desc) }
	has_many :line_items,:dependent=>:destroy
	has_many :item_orders,:dependent=>:destroy
	belongs_to :user
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			# item.cart_id=nil
			line_items<<item
		end
		
	end
	def total_price
		item_orders.to_a.sum{|item| item.total_price}
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	default_scope -> { order(created_at: :desc) }
	has_many :line_items
	validates :proname,presence:true,length:{maximum:255}
	validates :proprice,presence:true,:numericality =>{:greater_than_or_equal_to =>0.01}
	validates :proamount,presence:true,:numericality =>{allow_nil: true}
	mount_uploader :picture, PictureUploader
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders,:dependent=>:destroy
	before_save{self.email = email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name,presence:true,length:{maximum:20}
	validates :email,presence:true,length:{maximum:255},format:{with: VALID_EMAIL_REGEX},uniqueness:{case_sensitive:false}
	has_secure_password
	validates :password,length:{minimum:6},allow_blank:true

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 def show
 	 @cart=Cart.find(params[:id])
end
def destroy
	@cart = current_cart
	@cart.line_items.each do |item|
		@cart.emptycart(item.product.id)
	end
	@cart.destroy
	session[:cart_id] = nil
	redirect_to root_url
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
  	@cart = current_cart
  	if @cart.line_items.empty?
  		redirect_to root_url
  		flash[:danger]="cart is empty"
  	else
              @user = current_user
  		  @order=Order.new
  	end
  end
  def create
    	       @cart = current_cart
  		@order=Order.new(order_params)
             @order.add_line_items_from_cart(@cart)
  		if @order.save
                    @order.line_items.each do |item|
                            ItemOrder.create(order_id: @order.id,name: item.product.proname,amount: item.quantity,price:item.product.proprice)
                   end
        	       redirect_to @order
  			 @cart.destroy
			 session[:cart_id] = nil
  		else
  			render "new"
  		end
  end
  def show
  	@cart = current_cart
  	@order=Order.find(params[:id])
  end
  def index
    @cart = current_cart
    @user = current_user
    @orders = Order.all
    @current_orders = []
    @orders.each do |order|
      if order.user_id == @user.id
        @current_orders<<order
      end
    end
  end
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_url
  end
  private
  def order_params
  	params.require(:order).permit(:user_id,:name,:address,:email)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  	@product = Product.new
  end
   def create
  	@product = Product.new(product_parmas)
  	# @product.proprice.to_i
  	# @product.proamount.to_i
  	if @product.save
  		redirect_to @product
  	else
  		render 'new'
  	end
   end
   def destroy
   	@product = Product.find(params[:id]).destroy
   	redirect_to root_url
   end
   def edit
   	@product = Product.find(params[:id])
   end
   def update
   	@product = Product.find(params[:id])
   	if @product.update_attributes(product_parmas)
   		redirect_to @product
   	else
   		render 'new'
   	end
   end
   def show
   	@product = Product.find(params[:id])
   end
   def index
   	@products = Product.all
   end
   
   private
   def product_parmas
   	params.require(:product).permit(:proname,:proprice,:proamount,:picture)
   end
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  def destory
  end

  def model
  end

  def products
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def bye
  	@time = Time.now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "signup success"
              log_in @user
  		redirect_to @user
  	else
  		render "new"
  	end
  end
  def show
      @cart = current_cart
  	@user = User.find(params[:id])
  end
  def edit
      @cart = current_cart
      @user = User.find(params[:id])
  end
  def update
   @user = User.find(params[:id])
   if @user.update_attributes(user_params)
      flash[:success] = "update success"
      redirect_to @user
  else
    render "edit"
   end
  end
  private 
  def user_params
  	params.require(:user).permit(:name,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def baseTitle(diff='')
		base_title = "welcome depot"
		if diff.empty?
			base_title
		else
			"#{diff}|#{base_title}"
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end
	def current_user
		if @current_user.nil?
			@current_user = User.find_by(id: session[:user_id])
		else
			@current_user
		end
	end
	def logged_in?
		!current_user.nil?
	end
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<h1>cart</h1>
<ul>
<%@cart.line_items.each do |item|%>
	<li><%=item.quantity%>&times<%=item.product.proname%>小节：<%=number_to_currency(item.total_price)%></li>
	<%end%>
</ul>
总价：<%=number_to_currency(@cart.total_price)%></br>
<%=link_to "empty cart", @cart,:method=>:delete,data: { confirm: "You sure?" }%></br>
<%=link_to "order", new_order_path%></br>
<%=link_to "histroy order",orders_path%>

app/views/carts/show.html.erb
<%=render @cart%>

app/views/orders/index.html.erb
<h1>订单详情</h1>
<%if @current_orders.size>0%>
<%@current_orders.each do |order|%>
<ul>
<li>	
	<%=order.created_at%>&nbsp;&nbsp;&nbsp;&nbsp;
	联系人：<%=order.name%>
	联系地址：<%=order.address%>
	email：<%=order.email%>
</li>
<ul>
	<%order.item_orders.each do |item|%>
	
		<li>商品名：<%=item.name%>&nbsp;&nbsp;&nbsp;&nbsp;商品数量：<%=item.amount%>&nbsp;&nbsp;&nbsp;&nbsp;商品单价<%=item.price%>&nbsp;&nbsp;&nbsp;&nbsp;小计：<%=item.total_price%></li>
	<%end%>
	<li>合计：<%=order.total_price%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<%=link_to "delete",order,method: :delete,data:{confirm:"are you sure"}%>
	</li>
	</ul>
	
</ul>
<%end%>
<%else%>
<p>对不起，你还没有历史订单，请快去购物吧</p>
<%end%>

app/views/orders/new.html.erb
<h1>order info</h1>
<%=form_for(@order) do |f|%>
	<%=f.label :name%>
	<%=f.text_field :name%></br>
	<%=f.label :address%>
	<%=f.text_area :address%></br>
	<%=f.label :email%>
	<%=f.text_field :email%></br>
	<%=f.hidden_field :user_id,value: @user.id%></br>
	<%=f.submit "send_to_order"%>
<%end%>

app/views/orders/show.html.erb
<h1>恭喜你订单成功</h1>
联系人：<%=@order.name%></br>
联系地址：<%=@order.address%></br>
邮箱：<%=@order.email%></br>
	<strong>商品&nbsp;&nbsp;&nbsp;&nbsp;数量&nbsp;&nbsp;&nbsp;&nbsp;单价&nbsp;&nbsp;&nbsp;&nbsp;小计</strong></br>
<%@order.item_orders.each do |item|%>
	<%=item.name%>&nbsp;&nbsp;&nbsp;&nbsp;<%=item.amount%>&nbsp;&nbsp;&nbsp;&nbsp;<%=item.price%>&nbsp;&nbsp;&nbsp;&nbsp;<%=item.total_price%></br>
<%end%>
合计：<%=@order.total_price%></br>

<%=link_to "see_all_orders",orders_path%>

app/views/products/_form.html.erb
<%=form_for(@product,html:{multipart:true}) do |f|%>
	<%=render 'shared/error_messages',object: f.object%>
	<%=f.label :proname%>
	<%=f.text_field :proname%></br>

	<%=f.label :proprice%>
	<%=f.text_field :proprice%></br>
	
	<%=f.label :proamount%>
	<%=f.text_field :proamount%></br>

	<%=f.file_field :picture%></br>
	
	<%=f.submit 'add product'%>
<%end%>

app/views/products/edit.html.erb
<h1>修改商品</h1>
<%= render 'form'%>
<%=link_to "show",product_path%>
<%=link_to "all",product_path%>

app/views/products/index.html.erb
<h1>商品列表</h1>

<%@products.each do |product|%>
<p>
	商品名：<%=product.proname%>
	单价:<%=product.proprice%>
	剩余数量:<%=product.proamount%>
	<%if product.picture?%>
	<p>商品图片:<%=image_tag product.picture%></p>
	<%end%>
	<%=link_to '查看详情',product%>
	<%=link_to "修改",edit_product_path(product)%>
	<%=link_to '删除',product,method: :delete,data:{confirm:"are you sure"}%>
</p>
<%end%>
<%=link_to "添加商品",new_product_path%>

app/views/products/new.html.erb
<h1>add products</h1>
<%= render 'form'%>
<%=link_to "back",products_path%>

app/views/products/show.html.erb
<h1>购物详情列表</h1>
<p>商品名：<%=@product.proname%></p>
<p>商品单价：<%=@product.proprice%></p>
<p>商品数量：<%=@product.proamount%></p>
<%if @product.picture?%>
	<p>商品图片:<%=image_tag @product.picture%></p>
	<%end%>
<%=link_to 'see all products', products_path%>

app/views/users/edit.html.erb
<%=provide(:title,"updateuserinfo")%>
	<%=form_for(@user) do |f|%>
	<%=render 'shared/error_messages',object: f.object%>
	<%=f.label :name%>
	<%=f.text_field :name%></br>
	<%=f.label :email%>
	<%=f.text_field :email%></br>
	<%=f.label :password%>
	<%=f.password_field :password%></br>
	<%=f.label :password_confirmation,"Confirmation"%>
	<%=f.password_field :password_confirmation%></br>
	<%=f.submit "update"%>
<%end%>

app/views/users/new.html.erb
<%provide(:title,"signup")%>
<h1>signup</h1>
<%=form_for(@user) do |f|%>
	<%=render 'shared/error_messages',object: f.object%>
	<%=f.label :name%>
	<%=f.text_field :name%></br>
	<%=f.label :email%>
	<%=f.text_field :email%></br>
	<%=f.label :password%>
	<%=f.password_field :password%></br>
	<%=f.label :password_confirmation,"Confirmation"%>
	<%=f.password_field :password_confirmation%></br>

	<%=f.submit 'signup'%>
<%end%>

app/views/users/show.html.erb
<%=provide(:title,"show user")%>
用户名：<%=@user.name%></br>邮箱：<%=@user.email%>