config/routes.rb
Rails.application.routes.draw do  delete 'item_orders/destroy'
  get 'orders/new'
  get 'orders/show'

  get 'line_items/create'
  get 'login'=>"sessions#new"
  post 'login'=>"sessions#create"
  delete "logout"=>"sessions#destroy"
get 'signup' => 'users#new'
root 'static_pages#home'
  get 'hello'=>'say#hello'
  get 'bye'=>'say#bye'

  resources "products"
  resources "users"
  resources 'carts'
  resources 'orders'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items,:dependent=>:destroy
	def add_product(product_id)
		current_item= line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity+=1
			current_item.product.proamount-=1
			current_item.product.update_attributes(:proamount=>current_item.product.proamount)
		else
			current_item = line_items.build(:product_id=>product_id)
			current_item.product.proamount-=1
			current_item.product.update_attributes(:proamount=>current_item.product.proamount)
		end
		current_item
	end
	def emptycart(product_id)
		current_item= line_items.find_by_product_id(product_id)
		current_item.product.proamount+=current_item.quantity
		current_item.product.update_attributes(:proamount=>current_item.product.proamount)
	end
	def total_price
		line_items.to_a.sum{|item| item.total_price}
	end

end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
	belongs_to :order
	def total_price
		price * amount
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
	def total_price
		product.proprice * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	default_scope -> { order(created_at: :desc) }
	has_many :line_items,:dependent=>:destroy
	has_many :item_orders,:dependent=>:destroy
	belongs_to :user
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			# item.cart_id=nil
			line_items<<item
		end
		
	end
	def total_price
		item_orders.to_a.sum{|item| item.total_price}
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	default_scope -> { order(created_at: :desc) }
	has_many :line_items
	validates :proname,presence:true,length:{maximum:255}
	validates :proprice,presence:true,:numericality =>{:greater_than_or_equal_to =>0.01}
	validates :proamount,presence:true,:numericality =>{allow_nil: true}
	mount_uploader :picture, PictureUploader
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders,:dependent=>:destroy
	before_save{self.email = email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name,presence:true,length:{maximum:20}
	validates :email,presence:true,length:{maximum:255},format:{with: VALID_EMAIL_REGEX},uniqueness:{case_sensitive:false}
	has_secure_password
	validates :password,length:{minimum:6},allow_blank:true

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 def show
 	 @cart=Cart.find(params[:id])
end
def destroy
	@cart = current_cart
	@cart.line_items.each do |item|
		@cart.emptycart(item.product.id)
	end
	@cart.destroy
	session[:cart_id] = nil
	redirect_to root_url
end
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  def destory
  end

  def model
  end

  def products
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def bye
  	@time = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def baseTitle(diff='')
		base_title = "welcome depot"
		if diff.empty?
			base_title
		else
			"#{diff}|#{base_title}"
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end
	def current_user
		if @current_user.nil?
			@current_user = User.find_by(id: session[:user_id])
		else
			@current_user
		end
	end
	def logged_in?
		!current_user.nil?
	end
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=baseTitle(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>depot</h1>
<div>
	<%flash.each do |message_type,message|%>
		<div><%=message_type%>:<%=message%></div>
	<%end%>
</div>
<ul>
<li><%= link_to "Home",root_path %></li>
<%if logged_in?%>
<li>
<ul>
	<li><%=link_to "owner",current_user%></li>
	<li><%=link_to "settings",edit_user_path(current_user)%>
	<li><%=link_to "logout",logout_path,method:"delete"%></li>
</ul>
<%unless current_user.admin?%>
<%=render @cart%>
<%end%>
</li>
<%else%>
<li><%= link_to "Log in", login_path%></li>
<%end%>
</ul>
<%= yield %>
<div>
<%=debug(params) if Rails.env.development?%>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<%if object.errors.any?%>
<p>the form contains:<%=pluralize(object.errors.count,"error")%></p>
<ul>
	<%object.errors.full_messages.each do |msg|%>
	<li><%=msg%></li>
	<%end%>
</ul>
<%end%>